/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Mr Trung
 */
public class DangKy extends javax.swing.JFrame {
    PlaceHolder holder;
    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false); 
        holder = new PlaceHolder(txtTaiKhoan,"Tài Khoản");
        holder = new PlaceHolder(txtTenDN,"Tên Đăng Nhập");
        holder = new PlaceHolder(paPass,"Password");
        btnSubmit.requestFocus();
        setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\DA_CDJAVA\\build\\classes\\icon\\logo.png"));

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTaiKhoan = new javax.swing.JTextField();
        txtTenDN = new javax.swing.JTextField();
        paPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG KÝ TÀI KHOẢN");
        setMinimumSize(new java.awt.Dimension(680, 460));
        getContentPane().setLayout(null);

        txtTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTaiKhoan.setToolTipText("Nhập tài khoản của bạn");
        txtTaiKhoan.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtTaiKhoan);
        txtTaiKhoan.setBounds(420, 90, 202, 33);

        txtTenDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenDN.setToolTipText("Nhập tên của bạn");
        getContentPane().add(txtTenDN);
        txtTenDN.setBounds(420, 140, 202, 33);

        paPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paPass.setToolTipText("Nhập mật khẩu của bạn");
        getContentPane().add(paPass);
        paPass.setBounds(420, 191, 202, 33);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG KÝ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 49, 202, 22);

        btnCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(51, 204, 0));
        btnCreateAccount.setText("Tạo tài khoản");
        btnCreateAccount.setToolTipText("Nhấn để đồng ý tạo tài khoản");
        btnCreateAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 51)));
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateAccount);
        btnCreateAccount.setBounds(420, 242, 202, 37);

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setText("Bắt đầu");
        btnSubmit.setToolTipText("Nhấn vào để bắt đầu đăng ký");
        btnSubmit.setBorder(new javax.swing.border.MatteBorder(null));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(420, 350, 202, 37);

        btnLogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(204, 0, 0));
        btnLogin1.setText("Đăng nhập");
        btnLogin1.setToolTipText("Nhấn vào để đến trang đăng nhập");
        btnLogin1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin1);
        btnLogin1.setBounds(420, 297, 202, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pikachu3.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 390, 340);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg5.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 680, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        txtTaiKhoan.requestFocus();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        DangNhap frmDangNhap = new DangNhap();
        frmDangNhap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        String taikhoan = txtTaiKhoan.getText();
        String tendn = txtTenDN.getText();
        String matkhau = String.valueOf(paPass.getPassword());
        if(taikhoan.equals("") || tendn.equals("") || matkhau.equals("")){
            JOptionPane.showMessageDialog(this,"Bạn phải nhập đầy đủ thông tin","Thông báo", JOptionPane.INFORMATION_MESSAGE);
            paPass.requestFocus();
        }
        else {
            String errConnect = Connect.getConnection();
            if(!errConnect.equals("")){
                JOptionPane.showMessageDialog(this, errConnect ,"Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        else
            {
                String sql ="{call ThemUser(?,?,?,?,?)}";
                CallableStatement cstm;
                String kq;
                try{
                    cstm = Connect.conn.prepareCall(sql);
                    cstm.setString(1, taikhoan);
                    cstm.setString(2, tendn);
                    cstm.setString(3, matkhau);
                    cstm.setInt(4, 0);
                    cstm.registerOutParameter(5, java.sql.Types.NVARCHAR);
                    cstm.execute();
                    kq = cstm.getString(5);
                    JOptionPane.showMessageDialog(this,kq,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    cstm.close();
                    Connect.conn.close();

                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(this,"Lỗi: "+ ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
       }
    }//GEN-LAST:event_btnCreateAccountActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField paPass;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
