/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import jaco.mp3.player.MP3Player;
import java.awt.Dialog;
import java.awt.Toolkit;
import java.io.File;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mr Trung
 */
public class Pikachu extends javax.swing.JFrame {

    /**
     * Creates new form Trung
     */
    public Pikachu() {
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null);
        mP3Player.play();
        HienThi();
    }

    public static final String SONG =("D:\\DA_CDJAVA\\Music\\Nhacnen.mp3");
        MP3Player mP3Player = new MP3Player(new File(SONG));
    
        
    public void HienThi(){
        lblTenTKNC.setText(Connect.userID);
        lblTenNC.setText(Connect.name);
        lblTenNV.setText(Connect.name);
        setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\DA_CDJAVA\\build\\classes\\icon\\logo.png"));
        DocKetQua();
        
    }
    
    public void DocKetQua(){
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-G0I3AISP\\SQLEXPRESS01;databaseName=GAME;user=ChiTrung;password=180000");
            PreparedStatement st = conn.prepareStatement("select * from LICHSUGAME where UserID ='" + Connect.userID + "'");
            ResultSet rs = st.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbLichSu.getModel();
            while(rs.next()){
                Object objList[] = {rs.getDate("Thoi_Diem"), rs.getString("DIEM"), rs.getInt("Thoi_Gian"), rs.getString("Ket_Qua")};
                model.addRow(objList);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pikachu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPikachu = new javax.swing.JButton();
        btnDanhTuXi = new javax.swing.JButton();
        btnMoregame = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblHuongDanPikachu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLichSu = new javax.swing.JTable();
        btnXoaLichSu = new javax.swing.JButton();
        btnXoaTD = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnOnMusic = new javax.swing.JButton();
        btnOffMusic = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblTenNC = new javax.swing.JLabel();
        lblTenTKNC = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PIKACHU");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Chào bạn:");

        lblTenNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Các game bạn có thể chơi:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pikachu.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1200x628.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        btnPikachu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPikachu.setForeground(new java.awt.Color(255, 0, 0));
        btnPikachu.setText("Chơi game Pokemon");
        btnPikachu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        btnPikachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPikachuActionPerformed(evt);
            }
        });

        btnDanhTuXi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDanhTuXi.setForeground(new java.awt.Color(153, 0, 153));
        btnDanhTuXi.setText("Chơi game Đánh tù xì");
        btnDanhTuXi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        btnDanhTuXi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhTuXiActionPerformed(evt);
            }
        });

        btnMoregame.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        btnMoregame.setForeground(new java.awt.Color(0, 51, 255));
        btnMoregame.setText("More game...");
        btnMoregame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoregameActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 0, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTenNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnPikachu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDanhTuXi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoregame)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTenNV)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDanhTuXi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPikachu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnMoregame))
        );

        jTabbedPane2.addTab("Game của bạn", jPanel2);

        lblHuongDanPikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/OK_1.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ThatBai_1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Hình trên minh họa cách để chơi game. Đơn giản phải không nào, còn giờ thì chỉ cần bạn tìm ra các hình giống nhau trước thời gian là được !!!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblHuongDanPikachu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHuongDanPikachu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Hướng dẫn", jPanel3);

        jPanel4.setLayout(null);

        tbLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thời điểm", "Điểm", "Thời gian", "Kết quả"
            }
        ));
        jScrollPane1.setViewportView(tbLichSu);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(12, 68, 858, 375);

        btnXoaLichSu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoaLichSu.setForeground(new java.awt.Color(255, 0, 0));
        btnXoaLichSu.setText("Xóa Lịch Sử");
        btnXoaLichSu.setToolTipText("Nếu xóa hàng loạt không hiệu quả hãy xóa từng dòng bằng nút xóa theo dòng");
        btnXoaLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLichSuActionPerformed(evt);
            }
        });
        jPanel4.add(btnXoaLichSu);
        btnXoaLichSu.setBounds(184, 463, 172, 40);

        btnXoaTD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoaTD.setForeground(new java.awt.Color(255, 0, 0));
        btnXoaTD.setText("Xóa theo dòng");
        btnXoaTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTDActionPerformed(evt);
            }
        });
        jPanel4.add(btnXoaTD);
        btnXoaTD.setBounds(537, 461, 163, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("LỊCH SỬ GAME");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(12, 28, 858, 22);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg6.jpg"))); // NOI18N
        jPanel4.add(jLabel17);
        jLabel17.setBounds(0, 0, 920, 540);

        jTabbedPane2.addTab("Lịch sử", jPanel4);

        jPanel5.setLayout(null);

        btnOnMusic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOnMusic.setForeground(new java.awt.Color(0, 204, 0));
        btnOnMusic.setText("Bật nhạc nền");
        btnOnMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnMusicActionPerformed(evt);
            }
        });
        jPanel5.add(btnOnMusic);
        btnOnMusic.setBounds(310, 194, 207, 82);

        btnOffMusic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOffMusic.setForeground(new java.awt.Color(255, 0, 0));
        btnOffMusic.setText("Tắt nhạc nền");
        btnOffMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffMusicActionPerformed(evt);
            }
        });
        jPanel5.add(btnOffMusic);
        btnOffMusic.setBounds(310, 337, 207, 82);
        jPanel5.add(jSlider1);
        jSlider1.setBounds(310, 128, 207, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Min");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(264, 128, 28, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Max");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(535, 128, 32, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ÂM THANH");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(310, 58, 207, 29);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg6.jpg"))); // NOI18N
        jPanel5.add(jLabel15);
        jLabel15.setBounds(0, 0, 910, 560);

        jTabbedPane2.addTab("Tùy chỉnh", jPanel5);

        jPanel6.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THÔNG TIN NGƯỜI CHƠI");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(82, 47, 419, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tài khoản");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(82, 113, 104, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tên người chơi");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(82, 187, 104, 17);

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 0, 0));
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jPanel6.add(btnDangXuat);
        btnDangXuat.setBounds(182, 283, 290, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shatoshi2.gif"))); // NOI18N
        jPanel6.add(jLabel11);
        jLabel11.setBounds(530, 50, 160, 280);

        lblTenNC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenNC.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(lblTenNC);
        lblTenNC.setBounds(220, 180, 240, 33);

        lblTenTKNC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenTKNC.setForeground(new java.awt.Color(255, 0, 51));
        jPanel6.add(lblTenTKNC);
        lblTenTKNC.setBounds(220, 100, 281, 33);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg6.jpg"))); // NOI18N
        jPanel6.add(jLabel12);
        jLabel12.setBounds(0, 0, 920, 550);

        jTabbedPane2.addTab("Thông tin", jPanel6);

        jPanel1.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 255));
        jLabel18.setText("Họ tên SV: Phan Chí Trung");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(295, 57, 298, 53);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 255));
        jLabel19.setText("MSSV: 1800005414");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(295, 128, 298, 58);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg6.jpg"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, 0, 920, 560);

        jTabbedPane2.addTab("About", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void thoat(){
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE );//Nếu bấm đóng thì không làm gì cả mà hỏi người dùng trước
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(kq == 0)
        {
            System.exit(0);
        }
    }       
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        thoat();
    }//GEN-LAST:event_formWindowClosing

    private void btnPikachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPikachuActionPerformed
        Main frMain = new Main();
        mP3Player.pause();
        this.dispose();
        
    }//GEN-LAST:event_btnPikachuActionPerformed

    private void btnOnMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnMusicActionPerformed
        mP3Player.play();
    }//GEN-LAST:event_btnOnMusicActionPerformed

    private void btnOffMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffMusicActionPerformed
        mP3Player.pause();  
    }//GEN-LAST:event_btnOffMusicActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE );//Nếu bấm đóng thì không làm gì cả mà hỏi người dùng trước
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất không?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(kq == 0)
        {
            Connect.name = "";
            DangNhap frmDangNhap = new DangNhap();
            frmDangNhap.setVisible(true);
            this.dispose();
            mP3Player.pause();
        }
        
    }//GEN-LAST:event_btnDangXuatActionPerformed

    //---Thông tin thêm về các game sắp có
    private void btnMoregameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoregameActionPerformed
        JOptionPane.showMessageDialog(null, "Coming Soon","Thông tin",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMoregameActionPerformed

    //---Khi nhấn vào mở form game đánh tù xì
    private void btnDanhTuXiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhTuXiActionPerformed
        DanhTuXi frmDanhTuXi = new DanhTuXi();
        frmDanhTuXi.setVisible(true);
        mP3Player.pause();
        this.dispose();
    }//GEN-LAST:event_btnDanhTuXiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       thoat();
    }//GEN-LAST:event_btnThoatActionPerformed

    //---Xóa hàng loạt ---
    private void btnXoaLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLichSuActionPerformed
        String errConnect = Connect.getConnection();
        if(!errConnect.equals("")){
            JOptionPane.showMessageDialog(this, errConnect,"Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa lịch sử???","Xác nhận xóa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    
                    String sql ="{call sp_XoaLichSu(?,?)}";
                    CallableStatement cstm;
                    String kq;
              
                    cstm = Connect.conn.prepareCall(sql);
                    cstm.setString(1, Connect.userID);
                    cstm.registerOutParameter(2, java.sql.Types.NVARCHAR);
                    cstm.execute();
                    kq = cstm.getString(2);
                    JOptionPane.showMessageDialog(this,kq,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    cstm.close();
                    Connect.conn.close();                 
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, ex.getMessage(),"Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } 
 
    }//GEN-LAST:event_btnXoaLichSuActionPerformed

    //---Khi click vào dòng nào thì xóa dòng đó
    private void btnXoaTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTDActionPerformed
       if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa dòng này???","Xác nhận xóa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

       DefaultTableModel tableModel = (DefaultTableModel) tbLichSu.getModel();
       
            if(tbLichSu.getSelectedRowCount() == 1){
           tableModel.removeRow(tbLichSu.getSelectedRow());
            }
            else{
                if(tbLichSu.getRowCount() == 0){
                    JOptionPane.showMessageDialog(this,"Lịch sử rỗng");
                }else{
                    JOptionPane.showMessageDialog(this, "Chọn dòng cần xóa");
                }
            }
        }
    }//GEN-LAST:event_btnXoaTDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pikachu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDanhTuXi;
    private javax.swing.JButton btnMoregame;
    private javax.swing.JButton btnOffMusic;
    private javax.swing.JButton btnOnMusic;
    private javax.swing.JButton btnPikachu;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaLichSu;
    private javax.swing.JButton btnXoaTD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblHuongDanPikachu;
    private javax.swing.JLabel lblTenNC;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTenTKNC;
    private javax.swing.JTable tbLichSu;
    // End of variables declaration//GEN-END:variables
}
